version: '3'
services:
  madara-linux-arm:
    build:
      context: .
      dockerfile: Dockerfile.aarch64-unknown-linux-gnu
    image: madara-linux-arm
    container_name: madara-linux-arm-container
    volumes:
      - ../target/aarch64-unknown-linux-gnu/release:/app
