FROM --platform=linux/amd64 ubuntu:latest

RUN apt update && apt install -y \
    clang \
    llvm \
    libudev-dev \
    protobuf-compiler \
    libssl-dev \
    pkg-config \
    curl

COPY .. /app

WORKDIR /app

RUN curl https://sh.rustup.rs -sSf | bash -s -- -y

ENV PATH="/root/.cargo/bin:${PATH}"

RUN rustup target add x86_64-unknown-linux-gnu

RUN cargo build --release --target x86_64-unknown-linux-gnu
